# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df269716866255e202c42b3448ee2190e53d1ca633118d97ad901a21ccf3d1aede1a45a1dba2fbc2257ae66eb6658c9e9933caa0d883111431819dd6399719be

test:
  secret_key_base: 4112d8913a8521c61d4265f4fc8e28534a5d4222d1e52d44f5819c1b4fae552f044ad8e9742f4ac1c6f70c857cf93f831b1d9d444faffcb415a0218fc8a2b6b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
